version: '2'

services:
  db:
    image: 'postgis/postgis'
    environment:
     - POSTGRES_PASSWORD=smeMioUI4m12q
     - POSTGRES_USER=postgres
     - POSTGRES_DB=geoApp
     - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  api:
    restart: always
    build: ./api/
    volumes:
      - ./api/:/usr/src/app
    ports:
      - 5000:5000
    environment:
      FLASK_APP: 'app.py'
      PORT: 5000
      FLASK_DEBUG: 1